In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3,4,5])
print(a)
print(type(a))

print(a.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [3]:
b = np.array([[1], [2], [3], [4], [5]])
print(b)
print(type(b))

print(b.shape)

[[1]
 [2]
 [3]
 [4]
 [5]]
<class 'numpy.ndarray'>
(5, 1)


In [4]:
b[3][0]

4

In [5]:
c = np.array([[1, 2, 3], [4, 5, 6]])
print(c)
print(c.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


In [6]:
c[1][1]

5

In [7]:
# Create Zeros, Ones, Custom Array

a = np.zeros((3,3))

print(a)

b = np.ones((2,3))

print(b)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]


In [8]:
# Array of Some Constants

c = np.full((3,2), 5)

print(c)

[[5 5]
 [5 5]
 [5 5]]


In [9]:
# Identity Matrix - Size/Square matrix

d = np.eye(4)
print(d)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [10]:
# Random Matrix

randomMatrix = np.random.random((2,3))

print(randomMatrix)

[[0.9959905  0.65643419 0.57186734]
 [0.75320906 0.17602935 0.8465023 ]]


In [11]:
randomMatrix[ : ,1]

array([0.65643419, 0.17602935])

In [12]:
z = np.zeros((3,3))
print(z)
z[1,: ] = 5
z[ : ,-1] = 7

print(z)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[0. 0. 7.]
 [5. 5. 7.]
 [0. 0. 7.]]


In [13]:
# Datatypes 
print(z.dtype)



float64


In [14]:
z = np.zeros((3,3), dtype = np.int64)
print(z)
z[1,: ] = 5
z[ : ,-1] = 7


[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [15]:
print(z.dtype)

int64


In [16]:
# Mathematical Operations

x = np.array([[1,2], [3,4]])
y = np.array([[5,6], [7,8]])

# Element wise Addition, Substraction, Multiply, Division, square root
print(x+y)
print(np.add(x,y))
print("\n")

print(x-y)
print(np.subtract(x,y))
print("\n")


print(x*y)
print(np.multiply(x,y))
print("\n")

print(x/y)
print(np.divide(x,y))
print("\n")

# print(x/y)
print(np.sqrt(x))
print("\n")

[[ 6  8]
 [10 12]]
[[ 6  8]
 [10 12]]


[[-4 -4]
 [-4 -4]]
[[-4 -4]
 [-4 -4]]


[[ 5 12]
 [21 32]]
[[ 5 12]
 [21 32]]


[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


[[1.         1.41421356]
 [1.73205081 2.        ]]




In [17]:
# Matrix Multiplacation / Dot Product

print(x)
print(y)
print("\n")

print(x.dot(y))
print(np.dot(x,y))

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


In [18]:
# Multiplication (Dot Product) of Vectors => Scalar

a = np.array([1,2,3,4])
b = np.array([1,2,3,4])

print(a.dot(b))

30


In [19]:
print(a)

[1 2 3 4]


In [20]:
print(sum(a))

10


In [21]:
print(x)

[[1 2]
 [3 4]]


In [22]:
print(np.sum(x))
print(np.sum(x, axis = 1))

10
[3 7]


In [23]:
# Stacking of Arrays

print(a) 
b = b*2
b = b**2
print(b)

[1 2 3 4]
[ 4 16 36 64]


In [24]:
a=np.stack((a,b),axis=0)

In [25]:
# Reshape a Numpy Array

print(a)
print("\n")
a = a.reshape((-1,4))
print(a)

[[ 1  2  3  4]
 [ 4 16 36 64]]


[[ 1  2  3  4]
 [ 4 16 36 64]]


## Numpy Random Module

- rand : Random values in given shape.
- randn : Return a sample or samples from "standard normal" distribution.
- randint : Return random integers from low (inclusive) to high (exclusive).
- random : Return random floats in the half-open interval [0.0, 1.0)
- choice : Generates a sample from given 1-D array
- Shuffle : Shuffles the content of a sequence

In [26]:
import numpy as np

In [27]:
a = np.arange(10)
print(a)

print('\n')

b = np.arange(10)+5
print(b)

[0 1 2 3 4 5 6 7 8 9]


[ 5  6  7  8  9 10 11 12 13 14]


In [28]:
np.random.seed(1)
np.random.shuffle(a)
print(a)

[2 9 6 4 0 3 1 7 8 5]


In [29]:
#Return a sample or samples from "standard normal" distribution
a = np.random.randn(2,3)
print(a)

print('\n')

a = np.random.randint(5,10,3)
print(a)
print('\n')


# Randomly Pick one element from array

ele = np.random.choice([1,4,11,3,2,27])
print(ele)

[[ 1.5827523  -1.04514683  0.25759352]
 [-1.9593946  -1.50780766 -0.31529207]]


[7 9 6]


4


## Some More Numpy Functions - Statistics

- min, max
- mean
- median
- average
- variance
- standard deviation

In [30]:
a = np.array([[1,2,3,4],[7,6,2,0]])
print(a)
print(np.min(a))

#Specify the axis for direction in case of multi dimension array
print(np.min(a, axis = 0))
print(np.min(a, axis = 1))

[[1 2 3 4]
 [7 6 2 0]]
0
[1 2 2 0]
[1 0]


In [31]:
# Mean, Average of the elements
b = np.array([1,2,3,4,5])
m= sum(b)/5
print(m)

print(np.mean(b))
print(np.mean(a,axis = 0))
print(np.mean(a,axis = 1))

3.0
3.0
[4.  4.  2.5 2. ]
[2.5  3.75]


In [32]:
# Median of the elements

c = np.array([1,5,4,2,0])
print(np.median(c))


2.0


In [33]:
# Mean Vs Average
# Average is Weighted

print(np.mean(c))

# average is sum (c[i] * w[i])/n

w = np.array([1,2,3,4,5])
print(np.average(c, weights=w))

w = np.array([1,1,1,1,1])
print(np.average(c, weights=w))

2.4
2.066666666666667
2.4


In [34]:
# Standard Deviation

u = np.mean(c)
myStd = np.sqrt(np.mean(abs(c-u)**2))
print(myStd)

# Inbuilt Standard Deviation Function

dev = np.std(c)
print(dev)

# Variance

print(myStd**2)
print(np.var(c))

1.854723699099141
1.854723699099141
3.440000000000001
3.4400000000000004
